import{a as S,S as w,i as L}from"./assets/vendor-b11e2a50.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function c(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=c(t);fetch(t.href,r)}})();async function v(e,o){const c="44394014-4230f595acf8cb42e98735a97",s="https://pixabay.com",t="/api/",r=new URLSearchParams({key:c,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o}),n=`${s}${t}`;try{const a=await S.get(n,{params:r});if(a.status!==200)throw new Error("Failed to fetch images");const l=a.data;return{hits:l.hits,totalHits:l.totalHits}}catch(a){throw console.error("Error fetching the images:",a),a}}let u;function P(){const e=document.querySelector(".gallery");e.innerHTML=""}function E(e){const o=document.querySelector(".gallery"),c=e.map(({webformatURL:s,largeImageURL:t,tags:r,likes:n,views:a,comments:l,downloads:q})=>`
            <div class="photo-card">
                <a href="${t}" class="gallery-link">
                    <img src="${s}" alt="${r}"/>
                </a>
                <div class="info">
                    <p><b>Likes:</b> ${n}</p>
                    <p><b>Views:</b> ${a}</p>
                    <p><b>Comments:</b> ${l}</p>
                    <p><b>Downloads:</b> ${q}</p>
                </div>
            </div>
        `).join("");o.insertAdjacentHTML("beforeend",c),u&&u.destroy(),u=new w(".gallery a"),u.refresh()}function i(e){L.error({title:"Error",message:e,backgroundColor:"#ef4040",theme:"dark"})}function B(){const e=document.querySelector(".load-more-btn");e.style.display="block"}function f(){const e=document.querySelector(".load-more-btn");e.style.display="none"}function $(e,o){document.querySelector(".load-more-btn"),e>=o?(f(),i("We're sorry, but you've reached the end of search results.")):B()}const g=document.querySelector(".search-form"),m=document.querySelector(".loader"),M=g.querySelector('input[name="query"]'),O=document.querySelector(".load-more-btn"),H=document.querySelector(".gallery");let p="",d=1,h=1;const N=15;let y=[];g.addEventListener("submit",async e=>{if(e.preventDefault(),p=e.target.elements.query.value.trim(),p===""){f(),i("Please enter a search query.");return}m.style.display="block",f(),P(),d=1;try{await b(),M.value=""}catch(o){m.style.display="none",i(o.message)}});O.addEventListener("click",async()=>{try{d++,await b(),x()}catch(e){i(e.message)}});async function b(){const e=await v(p,d);y=e.hits,h=Math.ceil(e.totalHits/N),m.style.display="none",y.length===0?i("Sorry, there are no images matching your search query. Please try again!"):(E(y),$(d,h))}function x(){const o=H.querySelector(".photo-card").getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
